### ISSUE TITLE
Do we need to set a version of 1.77 or above?

### ISSUE THREAD

**Issue by weykon** [arufars/snippet-next#3]
it was blocking the Cursor editor, could you change the version demand ?

maybe ``` "engines": {
    "vscode": "^1.59.0",
  },```

I downloaded this extension then debugged there no error.

if there no relation of this snippet tool code with vscode engine too much, please change it

**Comment by arufars** [comment]
Thank you for your input. I will check into this request and evaluate the possibility of changing the required version of the VSCode engine. I will provide an update as soon as I have completed the evaluation.
