### ISSUE TITLE
TypeScript snippets

### ISSUE THREAD

**Issue by Klerith** [arufars/snippet-next#5]
Snippets like this, should appear on TypeScript files and not inside the TSX files.

rag   	 Create a function Route Handler API GET.
ragd	Create a function Route Handler API GET with Dynamic.
rags  	Create a function Route Handler API GET and Search.

Loving the extension btw!

**Comment by arufars** [comment]
Thank you for opening this issue! 🙌 I will adjust the settings to ensure that these snippets also appear in TypeScript files. I apologize for any inconvenience caused, and this support will be updated in version 0.2.0, along with exciting new features! 💪

I also appreciate your positive feedback on the extension I created! 😊 I'm thrilled to hear that you like it! 🎉

**Comment by arufars** [comment]
Thank you @Klerith  for your support and positive feedback! 

I'm glad to hear that this snippet is very timely for your online course update needs. I also thank you for your efforts in encouraging students to install my extension. 

I will continue to try to give my best. Thanks also for submitting another pull request with patch changes. I have checked your pull request.
