### ISSUE TITLE
Error Page Snippet

### ISSUE THREAD

**Issue by Klerith** [arufars/snippet-next#9]
Hi @arufars 

I would like to propone a new snippet to quickly create the error page, according to the official Next Docs
[Error page](https://nextjs.org/docs/app/building-your-application/routing/error-handling)

```
'use client' // Error components must be Client Components
 
import { useEffect } from 'react'
 
export default function Error({
  error,
  reset,
}: {
  error: Error
  reset: () => void
}) {
  useEffect(() => {
    // Log the error to an error reporting service
    console.error(error)
  }, [error])
 
  return (
    <div>
      <h2>Something went wrong!</h2>
      <button
        onClick={
          // Attempt to recover by trying to re-render the segment
          () => reset()
        }
      >
        Try again
      </button>
    </div>
  )
}
```

**Comment by arufars** [comment]
Thank you for your suggestion!  

I'm pleased to inform you that I have implemented the changes you proposed in my repository. The implementation I have made can be found here: [arufars/snippet-next#error](https://github.com/arufars/snippet-next#error). 

If you have any further questions or additional feedback, please don't hesitate to let me know. 

Thank you for opening the issue 🚀
